### ISSUE TITLE
Skip track from XBMC

### ISSUE THREAD

**Issue by steve1977** [juhovh/shairplay#32] opened 2014-09-02 14:05 UTC
First of all, huge thanks to this fantastic development. Absolutely fantastic!

One feature request - I would love to have the ability to skip to the next song from XBMC. For example, I am playing a playlist in itunes and output it to XBMC via airplay. If I don't like a song, I would love to skip to the next song from XBMC. Currently, I can do this from itunes, but from XBMC would be even better.

Thanks in advance for considering!

**Comment by juhovh** [comment] 2015-05-01 20:45
This is a valid feature, but I'm not sure if this should be part of shairplay library itself. What shairplay could do is to pass the DACP-ID to the calling client, but I think the actual DACP part should be in a separate library or script really. Documentation is at http://nto.github.io/AirPlay.html#audio-remotecontrol I wonder what @Memphiz has to comment on this, does Kodi support DACP in any way?

**Comment by juhovh** [comment] 2015-05-01 20:47
Actually let's continue this discussion in issue #30 instead which is a duplicate of this.

**Closed by juhovh** 2015-05-01 20:47 UTC

**Comment by Memphiz** [comment] 2015-05-15 09:44
@steve1977 you should reply to that

http://forum.kodi.tv/showthread.php?tid=224025&pid=2004503#pid2004503

**Comment by steve1977** [comment] 2015-05-15 12:20
Thanks for point me to this thread. Taking care of it now. Thanks!!!
